# Generated by Django 5.1.1 on 2024-09-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
